name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          java-package: 'jdk'
          architecture: 'x64'
          check-latest: false
          server-id: 'github'
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true
          job-status: 'success'
          
      - name: Install Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-6.3-bin.zip
          unzip gradle-7.6.3-bin.zip
          export PATH=$PATH:C:\Users\yulya\Documents\gradle-6.3

      - name: Build project
        run: gradle build

      - name: Run tests
        run: ./gradlew test --info --tests "co.edu.udea.certificacion.calidad.runners.SimulationBancolombia"
