name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build project
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test --info --tests "co.edu.udea.certificacion.calidad.runners.SimulationBancolombia"
